version: '3.8'

services:
  api:
    build:
      context: .
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
      - "5678:5678"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/fasthealth
    depends_on:
      - db
      - redis
      
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fasthealth
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata:
